[package]
name = "rust-chrome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.10"
winit = "0.26"
log = "0.4"
env_logger = "0.9"
